import { describe, it, expect } from 'vitest'
import { writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { check } from '../src/check'
import type { PromptRegistryConfig } from '../src/cli/config'

describe('check', () => {
  const tmpDir = join(tmpdir(), 'promptregistry-check-test-' + Date.now())
  const manifestPath = join(tmpDir, 'manifest.json')

  const config: PromptRegistryConfig = {
    manifestUrl: manifestPath,
    srcRoots: [join(tmpDir, 'src')],
    outDir: join(tmpDir, 'prompts', '.generated'),
  }

  function writeManifest(hash?: string) {
    mkdirSync(tmpDir, { recursive: true })
    const manifest = {
      'manifest-format-version': '1',
      prompts: [
        { name: 'greeting', version: 'v1', template: 'Hello {{name}}', delimiter: { open: '{{', close: '}}' } },
      ],
    }
    writeFileSync(manifestPath, JSON.stringify(manifest))
    return manifest
  }

  function writeLockfile(hash: string) {
    const lockfile = {
      'lockfile-format-version': '1',
      entries: [
        {
          name: 'greeting',
          version: 'v1',
          manifest_url: manifestPath,
          content_hash: hash,
          pulled_at: '2024-01-01T00:00:00.000Z',
        },
      ],
    }
    mkdirSync(config.outDir, { recursive: true })
    writeFileSync(join(config.outDir, 'prompt-lock.json'), JSON.stringify(lockfile, null, 2))
  }

  function writeGenerated(hash: string) {
    const content = `// Generated by promptregistry
// Manifest: ${manifestPath}
// Pin: greeting@v1
// Hash: ${hash}
// Generated: 2024-01-01T00:00:00.000Z

import { compile } from 'promptregistry/runtime'

export type GreetingVars = { name: string }

const _template = compile<GreetingVars>('Hello {{name}}', { open: '{{', close: '}}' })

export default _template
`
    mkdirSync(config.outDir, { recursive: true })
    writeFileSync(join(config.outDir, 'greeting.ts'), content)
  }

  it('passes when everything is in sync', async () => {
    writeManifest()
    const { hash } = await import('../src/manifest/fetcher').then((m) => m.fetchManifest(manifestPath))
    writeLockfile(hash)
    writeGenerated(hash)

    const result = await check(config)
    expect(result.ok).toBe(true)
    expect(result.errors).toHaveLength(0)
  })

  it('detects hash drift', async () => {
    writeManifest()
    writeLockfile('old-hash')
    writeGenerated('old-hash')

    const result = await check(config)
    expect(result.ok).toBe(false)
    expect(result.errors.some((e) => e.code === 'hash-drift')).toBe(true)
  })

  it('detects stale generated file', async () => {
    writeManifest()
    const { hash } = await import('../src/manifest/fetcher').then((m) => m.fetchManifest(manifestPath))
    writeLockfile(hash)
    writeGenerated('different-hash')

    const result = await check(config)
    expect(result.ok).toBe(false)
    expect(result.errors.some((e) => e.code === 'stale-dts')).toBe(true)
  })

  it('warns on orphaned lockfile entries', async () => {
    writeManifest()
    const { hash } = await import('../src/manifest/fetcher').then((m) => m.fetchManifest(manifestPath))
    // Write lockfile with an extra entry
    const lockfile = {
      'lockfile-format-version': '1',
      entries: [
        {
          name: 'greeting',
          version: 'v1',
          manifest_url: manifestPath,
          content_hash: hash,
          pulled_at: '2024-01-01T00:00:00.000Z',
        },
        {
          name: 'orphan',
          version: 'v1',
          manifest_url: manifestPath,
          content_hash: hash,
          pulled_at: '2024-01-01T00:00:00.000Z',
        },
      ],
    }
    mkdirSync(config.outDir, { recursive: true })
    writeFileSync(join(config.outDir, 'prompt-lock.json'), JSON.stringify(lockfile, null, 2))
    writeGenerated(hash)

    const result = await check(config)
    expect(result.ok).toBe(true) // warnings don't fail
    expect(result.warnings.some((w) => w.code === 'orphaned-entry')).toBe(true)
  })

  // Cleanup
  it('cleanup', () => {
    rmSync(tmpDir, { recursive: true, force: true })
  })
})
