/**
 * Codegen — emit one runtime `.ts` per prompt and the `registry.ts` barrel.
 *
 * Issues 004 and 005.
 *
 * Each generated `<name>.ts` file imports from `promptregistry/runtime`,
 * inlines the template and delimiter, and exports a default
 * `CompiledTemplate<…>`. The header comment carries the metadata that
 * `check` and `check --tsc` parse.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Manifest, PromptEntry } from '../manifest/schema.js'

export interface CodegenOptions {
  outDir: string
  manifestUrl: string
  manifestHash: string
}

const NAME_REGEX = /^[A-Za-z0-9-_]+$/

export function codegen(manifest: Manifest, options: CodegenOptions): void {
  mkdirSync(options.outDir, { recursive: true })

  // Collision detection up front — we don't want to write half the files
  // and then bail in the middle.
  const identifiers = new Map<string, string>()
  const typeNames = new Map<string, string>()
  const collisions: Array<[string, string, string]> = []

  for (const entry of manifest.prompts) {
    if (!NAME_REGEX.test(entry.name)) {
      throw new Error(`Invalid prompt name "${entry.name}" — must match ${NAME_REGEX.source}`)
    }
    const id = kebabToCamel(entry.name)
    const previousId = identifiers.get(id)
    if (previousId && previousId !== entry.name) {
      collisions.push(['identifier', previousId, entry.name])
    } else {
      identifiers.set(id, entry.name)
    }

    const typeName = `${pascalCase(entry.name)}Vars`
    const previousType = typeNames.get(typeName)
    if (previousType && previousType !== entry.name) {
      collisions.push(['type-name', previousType, entry.name])
    } else {
      typeNames.set(typeName, entry.name)
    }
  }

  if (collisions.length > 0) {
    const details = collisions.map(([kind, a, b]) => `${kind}: "${a}" and "${b}"`).join(', ')
    throw new Error(`Identifier collision: ${details}`)
  }

  // Emit one runtime .ts per prompt
  for (const entry of manifest.prompts) {
    const tsContent = generateRuntime(entry, options)
    writeFileSync(join(options.outDir, `${entry.name}.ts`), tsContent)
  }

  // Emit registry.ts barrel
  const registryContent = generateRegistry(manifest)
  writeFileSync(join(options.outDir, 'registry.ts'), registryContent)
}

function generateRuntime(entry: PromptEntry, options: CodegenOptions): string {
  const pin = `${entry.name}@${entry.version}`
  const placeholders = extractPlaceholders(entry.template, entry.delimiter.open, entry.delimiter.close)
  const typeName = `${pascalCase(entry.name)}Vars`
  const varsType = placeholders.length > 0
    ? `{\n${placeholders.map((p) => `  ${p}: string`).join('\n')}\n}`
    : 'Record<string, never>'

  return `// Generated by promptregistry — do not edit by hand
// Manifest: ${options.manifestUrl}
// Pin: ${pin}
// Hash: ${options.manifestHash}

import { compile } from 'promptregistry/runtime'

export type ${typeName} = ${varsType}

const _template = compile<${typeName}>(
  ${JSON.stringify(entry.template)},
  { open: ${JSON.stringify(entry.delimiter.open)}, close: ${JSON.stringify(entry.delimiter.close)} },
)

export default _template
`
}

function generateRegistry(manifest: Manifest): string {
  const lines: string[] = ['// Generated by promptregistry — do not edit by hand']
  for (const entry of manifest.prompts) {
    const identifier = kebabToCamel(entry.name)
    lines.push(`export { default as ${identifier} } from './${entry.name}.js'`)
  }
  return lines.join('\n') + '\n'
}

function kebabToCamel(str: string): string {
  return str.replace(/[-_]([A-Za-z0-9])/g, (_, char: string) => char.toUpperCase())
}

function pascalCase(str: string): string {
  const camel = kebabToCamel(str)
  return camel.charAt(0).toUpperCase() + camel.slice(1)
}

function extractPlaceholders(template: string, open: string, close: string): string[] {
  const regex = new RegExp(
    `${escapeRegex(open)}([A-Za-z_][A-Za-z0-9_]*)${escapeRegex(close)}`,
    'g',
  )
  const matches = [...template.matchAll(regex)].map((m) => m[1])
  return [...new Set(matches)]
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
