/**
 * Runtime helper consumed by codegen-emitted files.
 *
 * Exposed via the `promptregistry/runtime` subpath. Not part of the
 * documented SDK surface (per ADR-0004): the only intended caller is
 * code generated by `promptregistry codegen`.
 *
 * Built on `@nkwib/tprompt` for placeholder extraction and rendering.
 * PromptRegistry keeps its own `CompiledTemplate<Vars>` type (an explicit
 * generic, not the literal-type inference tprompt's own `Compiled` type
 * uses) because codegen emits a named `XxxVars` type per prompt and
 * `check --tsc` matches tsc diagnostics against that name; tprompt's
 * inferred, anonymous object types would not carry it.
 */

import { makePromptTag, MissingPlaceholderError } from '@nkwib/tprompt'

export interface CompiledTemplate<Vars extends Record<string, string> = Record<string, string>> {
  readonly strings: TemplateStringsArray
  readonly placeholders: readonly string[]

  with(vars: Vars): string

  partial(vars: Partial<Vars>): CompiledTemplate<Vars>

  validate(schema: unknown): string
  validateSafe(schema: unknown): { success: true; data: string } | { success: false; error: Error }
}

export interface PromptTag {
  <Strings extends TemplateStringsArray>(
    strings: Strings,
    ...values: unknown[]
  ): CompiledTemplate
}

export interface CompileDelimiter {
  open: string
  close: string
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function toTemplateStringsArray(template: string): TemplateStringsArray {
  return Object.assign([template], { raw: [template] }) as unknown as TemplateStringsArray
}

function buildCompiled<Vars extends Record<string, string>>(
  template: string,
  delimiter: CompileDelimiter,
): CompiledTemplate<Vars> {
  const tag = makePromptTag(delimiter)
  const compiled = tag(template)

  function withVars(vars: Vars): string {
    try {
      return compiled.with(vars as Record<string, never>)
    } catch (error) {
      if (error instanceof MissingPlaceholderError) {
        throw new Error(`Missing variable: ${error.missing[0]}`)
      }
      throw error
    }
  }

  function partial(vars: Partial<Vars>): CompiledTemplate<Vars> {
    let result = template
    for (const placeholder of compiled.placeholders) {
      const value = (vars as Record<string, string | undefined>)[placeholder]
      if (value !== undefined) {
        const pattern = new RegExp(
          `${escapeRegex(delimiter.open)}${placeholder}${escapeRegex(delimiter.close)}`,
          'g',
        )
        result = result.replace(pattern, String(value))
      }
    }
    return buildCompiled<Vars>(result, delimiter)
  }

  return {
    strings: toTemplateStringsArray(template),
    placeholders: compiled.placeholders,
    with: withVars,
    partial,
    validate(_schema: unknown): string {
      return withVars({} as Vars)
    },
    validateSafe(_schema: unknown) {
      try {
        return { success: true as const, data: withVars({} as Vars) }
      } catch (error) {
        return {
          success: false as const,
          error: error instanceof Error ? error : new Error(String(error)),
        }
      }
    },
  }
}

export function compile<TVars extends Record<string, string> = Record<string, string>>(
  template: string,
  delimiter: CompileDelimiter,
): CompiledTemplate<TVars> {
  return buildCompiled<TVars>(template, delimiter)
}
