/**
 * Runtime helper consumed by codegen-emitted files.
 *
 * Exposed via the `promptregistry/runtime` subpath. Not part of the
 * documented SDK surface (per ADR-0004) — the only intended caller is
 * code generated by `promptregistry codegen`.
 */

import { makePromptTag, type CompiledTemplate } from './promptkit.js'

export type { CompiledTemplate } from './promptkit.js'

export interface CompileDelimiter {
  open: string
  close: string
}

export function compile<TVars extends Record<string, string> = Record<string, string>>(
  template: string,
  delimiter: CompileDelimiter,
): CompiledTemplate<TVars> {
  const tag = makePromptTag(delimiter)
  const strings = Object.assign([template], { raw: [template] }) as unknown as TemplateStringsArray
  return tag(strings) as unknown as CompiledTemplate<TVars>
}
